<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [4]:
[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
A   = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]

B   = [[1, 0, 0], [0, 1, 0], [0, 0, 1]] 
def matrix_mul(A, B):
    return [[sum(i * j for i, j in zip(r, c)) for c in zip(*B)]
        for r in A]
matrix_mul(A, B)      


[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

In [ ]:
A   = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]

B   = [[1, 0, 0], [0, 1, 0], [0, 0, 1]] 
def matrix_mul(A, B):
    for r in A:
        for c in B:
        for j in zip(r,c):
            sum += [i*j]
            
    
                
        

In [14]:
A = [[1, 2], [3, 4]]
B = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]
def matrix_mul(A, B):
    return [[sum(i * j for i, j in zip(r, c)) for c in zip(*B)]
        for r in A]
matrix_mul(A, B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

In [ ]:
A = [[1, 2], [3, 4]]
B = [[1, 4], [5, 6], [7, 8], [9, 6]]
def matrix_mul(A, B):
    return [[sum(i * j for i, j in zip(r, c)) for c in zip(*B)]
        for r in A]
matrix_mul(A, B)

[[11, 16], [23, 36]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
def pick_a_number_from_list(A):
   weights1=[]

   for i in A:
        weights1.append(i/sum(A))
        
   selected_random_number = random.choices(A,weights=weights1,k=1)    
    
   return selected_random_number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

[100]
[27]
[100]
[79]
[100]
[27]
[27]
[100]
[10]
[45]
[100]
[28]
[28]
[79]
[45]
[45]
[100]
[100]
[13]
[79]
[100]
[79]
[45]
[100]
[100]
[45]
[100]
[28]
[100]
[5]
[100]
[100]
[27]
[100]
[45]
[100]
[79]
[100]
[27]
[79]
[100]
[100]
[45]
[45]
[5]
[5]
[45]
[28]
[28]
[79]
[79]
[79]
[100]
[45]
[79]
[27]
[100]
[79]
[79]
[100]
[27]
[100]
[45]
[100]
[100]
[79]
[45]
[10]
[100]
[100]
[100]
[13]
[100]
[79]
[100]
[100]
[100]
[100]
[79]
[100]
[100]
[45]
[45]
[28]
[100]
[45]
[100]
[79]
[100]
[28]
[79]
[100]
[79]
[79]
[79]
[28]
[100]
[100]
[100]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [28]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
A =  ['234',
'a2b3c4',
'abc',
'#2a$#b%c%561#']
for A in A:
    new_s = '#' * len(re.sub(r'\D', '', A))
    print('Input = {} output = {}'.format(A,new_s))

Input = 234 output = ###
Input = a2b3c4 output = ###
Input = abc output = 
Input = #2a$#b%c%561# output = ####


# <h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [83]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
import numpy as np

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def display_dash_board(students, marks):
    


    dictionary = dict(zip(Students,Marks))
    
    max_mark = max(Marks)
    min_mark = min(Marks)
    diff = max_mark - min_mark 
    percentile_25 = diff*0.25 
    percentile_75 = diff*0.75
    
    
    
    print("maximum marks")
    print(max_mark)
    print("minimum marks")
    print(min_mark )
    print("difference")
    print(diff)
    print("percentile_25")
    print(percentile_25)
    print("percentile_75")
    print(percentile_75)

    
    
    print("**********************************")

    print('top_5_students = A')

    for key, value in sorted(dictionary.items(), key=lambda item: item[1],reverse=True)[:5]:
    
          print("%s: %s" % (key, value))
        
          

    print("************************************")


    print('least_5_students = B')

    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
          print("%s: %s" % (key, value))
        
    print("************************************************") 
    
    
   
    
    
          
            
          

display_dash_board(Students, Marks)

maximum marks
98
minimum marks
12
difference
86
percentile_25
21.5
percentile_75
64.5
**********************************
top_5_students = A
student8: 98
student10: 80
student2: 78
student5: 48
student7: 47
************************************
least_5_students = B
student3: 12
student4: 14
student9: 35
student6: 43
student1: 45
************************************************


In [88]:
max_mark = max(Marks)
min_mark = min(Marks)
diff = max_mark - min_mark 
percentile_25 = diff*0.25 
percentile_75 = diff*0.75

In [91]:



res = {s: m for s, m in sorted(zip(Students, Marks), key=lambda i: i[1]) if m > percentile_25  and m <  percentile_75}
res  

{'student9': 35,
 'student6': 43,
 'student1': 45,
 'student7': 47,
 'student5': 48}

# <h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [12]:
points = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
points.sort()
print(points)

(6, -7): 0.06512516333438509


In [11]:
 points = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
query = (3,-4)
dist = []
for point in points:
    numerator = (point[0]*query[0])+point[1]*query[1]
    denomerator = ((point[0]**2+point[1]**2)**0.5)*((query[0]**2+query[1]**2)**0.5)
    dist.append(math.acos(numerator/denomerator))
dictionary = dict(zip(points,dist))
for key, value in sorted(dictionary.items(), key=lambda item: item[1], reverse=False)[:5]:

   print("%s: %s" % (key, value))    

(6, -7): 0.06512516333438509
(1, -1): 0.14189705460416438
(6, 0): 0.9272952180016123
(-5, -8): 1.2021004241368467
(-1, -1): 1.4288992721907328


In [4]:
points = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
query = (3,-4)
dist = []
for point in points:
    numerator = (point[0]*query[0])+point[1]*query[1]
    denomerator = ((point[0]**2+point[1]**2)**0.5)*((query[0]**2+query[1]**2)**0.5)
    dist.append(math.acos(numerator/denomerator))
dictionary = dict(zip(points,dist))
for key, value in sorted(dictionary.items(), key=lambda item: item[1], reverse=True):

   print("%s: %s" % (key, value))    

(-1, 1): 2.9996955989856287
(0, 6): 2.498091544796509
(1, 2): 2.0344439357957027
(3, 4): 1.8545904360032246
(-1, -1): 1.4288992721907328
(-5, -8): 1.2021004241368467
(6, 0): 0.9272952180016123
(1, -1): 0.14189705460416438
(6, -7): 0.06512516333438509


In [5]:
closest_points = [i[0] for i in sorted(enumerate(dist), key = lambda x:x[1])][:5]
for i in closest_points:
    print(i)

3
8
7
5
6


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
  for i in red:
        eq=line.replace('x','*'+str(i[0]))
        eq=eq.replace('y','*'+str(i[1]))
        answer=eval(eq)
        if answer>0:
            pass
        else:
            return "NO"
        
    # Code for Blue
  for j in blue:

        eq1=line.replace('x','*'+str(j[0]))
        eq1=eq1.replace('y','*'+str(j[1]))
        answer1=eval(eq1)
        if answer1<0:
            pass
        else:
            return "NO"
  return "Yes"
    
  
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

Yes
NO
NO
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    blank_count=0
    value_count = 0
    splitString = string.split(",")
    print("Input:",string)
    #print(string)
    totalNumbers = len(splitString)
    for i in splitString:
        if i=="_":
            blank_count+=1
        else:
            value_count=int(i)+int(value_count)
    sequenceNumber = int(value_count/totalNumbers)
    if(blank_count!=0):
        output = string.replace("_",str(sequenceNumber),blank_count)
        print(output)

    

S=  "_,_,30,_,_,_,50,_,_"


smoothed_values= curve_smoothing(S)
       

Input: _,_,30,_,_,_,50,_,_
8,8,30,8,8,8,50,8,8


In [ ]:
def curve_smoothing(string):
    blank_count=0
    value_count = 0
    splitString = string.split(",")
    print("Input:",string)
    #print(string)
    totalNumbers = len(splitString)
    for i in splitString:
        if i=="_":
            blank_count+=1
        else:
            value_count=int(i)+int(value_count)
    sequenceNumber = int(value_count/totalNumbers)
    if(blank_count!=0):
        output = string.replace("_",str(sequenceNumber),blank_count)
        print(output)
S= "_,_,_,24"
smoothed_values= curve_smoothing(S)


Input: _,_,_,24
6,6,6,24


In [ ]:
def curve_smoothing(string):
    blank_count=0
    value_count = 0
    splitString = string.split(",")
    print("Input:",string)
    #print(string)
    totalNumbers = len(splitString)
    for i in splitString:
        if i=="_":
            blank_count+=1
        else:
            value_count=int(i)+int(value_count)
    sequenceNumber = int(value_count/totalNumbers)
    if(blank_count!=0):
        output = string.replace("_",str(sequenceNumber),blank_count)
        print(output)
S= "40,_,_,_,60"
smoothed_values= curve_smoothing(S)


Input: 40,_,_,_,60
40,20,20,20,60


In [ ]:
def curve_smoothing(string):
    blank_count=0
    value_count = 0
    splitString = string.split(",")
    print("Input:",string)
    #print(string)
    totalNumbers = len(splitString)
    for i in splitString:
        if i=="_":
            blank_count+=1
        else:
            value_count=int(i)+int(value_count)
    sequenceNumber = int(value_count/totalNumbers)
    if(blank_count!=0):
        output = string.replace("_",str(sequenceNumber),blank_count)
        print(output)
S= "80,_,_,_,_"
smoothed_values= curve_smoothing(S)


Input: 80,_,_,_,_
80,16,16,16,16


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [27]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]

dictionary1 = {
'F1S1': 0,
'F2S1': 0,
'F3S1': 0,
'F4S1': 0,
'F5S1': 0,
'F1S2': 0,
'F2S2': 0,
'F3S2': 0,
'F4S2': 0,
'F5S2': 0,
'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

dictionary2 = {
'S1': 0,
'S2': 0,
'S3': 0
}


def compute_conditional_probabilites(A):
    for i in range(len(A)):
       k = A[i][0] + A[i][1]
       dictionary1[k] += 1
       dictionary2[A[i][1]] += 1

compute_conditional_probabilites(A)
print('Probability of P(F=F1|S==S1)', (dictionary1['F4S3']/dictionary2['S3']))

Probability of P(F=F1|S==S1) 0.3333333333333333


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [22]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
      
      S1 = S1.split(" ")
      S2 = S2.split(" ")
      return len(list(set(S1)&set(S2)))

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a = string_features(S1,S2)
print("a.",a)



a. 7


In [26]:
def string_features(S1, S2):
   # count
   count = {}
   # insert in S1
   for word in S1.split():
      count[word] = count.get(word, 0) + 1
   # insert in S2
   for word in S2.split():
      count[word] = count.get(word, 0) + 1
   # return ans
   return [word for word in count if count[word] == 1]
# main
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

print("b,c.",string_features(S1, S2))


b,c. ['first', 'F', '5', 'second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [97]:
def logloss(S):
    temp = []
    total = 0
    for x,y in A:
        temp.append(sum([int(x)*math.log10(float(y))+ (1-int(x))*math.log10(1-float(y))]))
        total = sum(temp)
        log = (-1/8)*total
    
    return log
    
    
    
    

In [98]:
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
print(logloss(A))

0.42430993457031635
